### ISSUE TITLE
mifm?

### ISSUE THREAD

**Issue by vivalaflam** [kkszysiu/mifm#10]
the app in chinese says RoidMi 

also, somebody changed the title in-app saying xiaomi mifm?

**Comment by kkszysiu** [comment]
Okay guys,

We should standardize the app names between languages.

This was a change suggested by Igor, but I agree that RoidMi would be a
better name.

Igor, what do you think?
05.04.2016 8:10 PM "vivalaflam" notifications@github.com napisał(a):

**Comment by vivalaflam** [comment]
what I think should be happening is that the other languages should be based on the English translation, since I directly translated it from the original chinese language, and kept all the names.
I thought the other guys base their translation on the english one and not on the chinese one?

**Comment by kkszysiu** [comment]
@IgorTimoshenko is it okay for you to bring back the old name?

**Comment by ihortymoshenko** [comment]
Hello!

What is the difference between RoidMi and MiFM? AFAIK RoidMi is the device name and MiFM is the app name so I changed the app name in the translations. I have a few other apps from Xiaomi and they are have the Mi prefix in their names.

**Comment by vivalaflam** [comment]
that is because the products are called Mixxx (miband for example.) this is called roidmi. mifm is the apks name for ease.
you would be correct, if roidmi was called miroidmi :P

there's the difference.

the chinese apps name is roidmi fm.

not mifm nor xiaomi fm or anything else. im just trying to do things the right way.

**Comment by kkszysiu** [comment]
Okay guys, let's bring back old name maybe.

@vivalaflam @IgorTimoshenko 
Agreed?

**Comment by ihortymoshenko** [comment]
@kkszysiu, `MiFM` -> `RoidMi` && `Xiaomi MiFM` -> `Xiaomi RoidMi`?

P.S. What about repository name and README?
P.P.S. Why the original apk file contain the `mifm` string? :)

**Comment by ihortymoshenko** [comment]
@vivalaflam, about Mi Band. Mi Band is the device name. The app name is Mi Fit. Do you know why?

**Comment by kkszysiu** [comment]
@IgorTimoshenko my names of repo etc was basically a base string from apk name.

But if in Chinese app is called RoidMi, then maybe its better to stick with that name. And "RoidMi" name contains "Mi" in a name :)

**Comment by vivalaflam** [comment]
@igortimoshenko
yes actually "mi" is an interpretation for "my" (ss my band - my fit)
another example. the xiaomi mi series phones. that mi is as in mine/my. same principle.
the most correct name for the app is RoidMi FM.

there's no need to mention xiaomi because "mi" is their trademark.

**Comment by ihortymoshenko** [comment]
@kkszysiu, @vivalaflam, ok
